spring:
  datasource:
    username: grocery_store_delivery
    password: grocery_store_delivery
    url: jdbc:mysql://localhost:3306/grocery_store_delivery
    
  jpa:
    hibernate:
       ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always